# Generated by Django 4.2.4 on 2023-10-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('grandfather_name', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('identity_type', models.CharField(max_length=20)),
                ('identity_number', models.CharField(max_length=20)),
                ('identity_documents_front', models.FileField(blank=True, null=True, upload_to='identity/%Y/%m/%d/front/')),
                ('identity_documents_back', models.FileField(blank=True, null=True, upload_to='identity/%Y/%m/%d/back/')),
                ('secondary_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('whatsapp_viber_number', models.CharField(max_length=20)),
                ('permanent_address_country', models.CharField(max_length=100)),
                ('permanent_address_state', models.CharField(max_length=100)),
                ('permanent_address_district', models.CharField(max_length=100)),
                ('permanent_address_municipality', models.CharField(max_length=100)),
                ('permanent_address_city_village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_ward_no', models.CharField(max_length=10)),
                ('is_current_address_same_as_permanent', models.BooleanField(default=True)),
                ('current_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_city_village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('highest_education', models.CharField(max_length=100)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
