# Generated by Django 4.2.4 on 2023-10-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorkyc',
            options={'verbose_name': 'KYC', 'verbose_name_plural': 'KYC'},
        ),
    ]
