# Generated by Django 4.2.4 on 2023-12-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_visitorkyc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorkyc',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitorkyc',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
    ]
