# Generated by Django 4.2.4 on 2024-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_alter_visitorkyc_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorkyc',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
