# Generated by Django 4.2.4 on 2024-02-22 02:46

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_visitorsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsmessage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='visitors/messages', validators=[common.utils.validate_image_size]),
        ),
    ]
