# Generated by Django 4.2.4 on 2023-10-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='organization',
            new_name='user',
        ),
    ]
