# Generated by Django 4.2.4 on 2024-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Attach_File', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
