# Generated by Django 4.2.4 on 2024-01-27 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_notificationdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationdata',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notification'},
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_org_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
