# Generated by Django 4.2.4 on 2024-02-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notificationdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdata',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
