# Generated by Django 4.2.4 on 2024-02-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notificationdata_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationdata',
            old_name='Attach_File',
            new_name='attach_file',
        ),
        migrations.RenameField(
            model_name='notificationdata',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notificationdata',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='notificationdata',
            name='Notification_Type',
        ),
        migrations.RemoveField(
            model_name='notificationdata',
            name='Target_audience',
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='audience',
            field=models.CharField(blank=True, choices=[('visitor', 'Visitor'), ('branch', 'Branch'), ('all', 'All')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('promotional', 'Promotional'), ('wishes', 'Wishes'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
