# Generated by Django 4.2.4 on 2023-10-10 07:52

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_number', models.CharField(max_length=10, unique=True, validators=[user.models.validate_mobile_number])),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sms_verified', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=250, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('private', 'Private'), ('non-government', 'Non-Government'), ('government', 'Government'), ('public', 'Public'), ('educational', 'Educational'), ('healthcare', 'Healthcare'), ('research', 'Research'), ('non-profit', 'Non-Profit'), ('technology', 'Technology'), ('financial', 'Financial'), ('entertainment', 'Entertainment'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('environmental', 'Environmental'), ('arts-and-culture', 'Arts and Culture'), ('social-services', 'Social Services'), ('sports', 'Sports'), ('media', 'Media'), ('religious', 'Religious'), ('other', 'Other')], max_length=20, null=True)),
                ('organization_nature', models.CharField(blank=True, choices=[('service-based', 'Service Based'), ('product-based', 'Product Based'), ('non-profit', 'Non Profit'), ('educational', 'Educational'), ('healthcare', 'Healthcare'), ('research', 'Research'), ('technology', 'Technology'), ('financial', 'Financial'), ('entertainment', 'Entertainment'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('environmental', 'Environmental'), ('arts-and-culture', 'Arts and Culture'), ('social-services', 'Social Services'), ('sports', 'Sports'), ('media', 'Media'), ('religious', 'Religious'), ('other', 'Other')], max_length=20, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/%Y/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_visitor', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('approve_visitor_before_access', models.BooleanField(default=False)),
                ('check_in_check_out_feature', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
