# Generated by Django 4.2.4 on 2024-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_is_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
