# Generated by Django 4.2.4 on 2024-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_visitors',
            field=models.BooleanField(default=False),
        ),
    ]
