# Generated by Django 4.2.4 on 2024-01-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_approved_visitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='approved_visitors',
            new_name='approve_visitors',
        ),
    ]
