# Generated by Django 4.2.4 on 2024-01-04 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_admin_of_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='validation_token_of_organization',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
