# Generated by Django 4.2.4 on 2024-01-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_validation_token_of_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='update ORG address', max_length=200),
            preserve_default=False,
        ),
    ]
