# Generated by Django 4.2.4 on 2024-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customuser_id_number_customuser_type_of_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='type_of_id',
        ),
    ]
