# Generated by Django 4.2.4 on 2024-01-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_roleofuser_active_roleofuser_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleOfUser',
            new_name='UsersStaffWithRole',
        ),
    ]
