# Generated by Django 4.2.4 on 2024-01-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_roleofuser_usersstaffwithrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersStaffWithRole',
        ),
    ]
