# Generated by Django 4.2.4 on 2024-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_usersstaffwithrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='qr/%Y/'),
        ),
    ]
