# Generated by Django 4.2.4 on 2024-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_subscription_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='lock_org',
            field=models.BooleanField(default=False),
        ),
    ]
