# Generated by Django 4.2.4 on 2023-10-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationbranch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='organizationdocument',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='organizationkyc',
            options={'verbose_name': 'KYC', 'verbose_name_plural': 'KYC'},
        ),
        migrations.AlterModelOptions(
            name='organizationsocialmedialink',
            options={'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.AlterModelOptions(
            name='organizationvisithistory',
            options={'verbose_name': 'Hisitoy', 'verbose_name_plural': 'Histories'},
        ),
    ]
