# Generated by Django 4.2.4 on 2023-10-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organizationbranch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkyc',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
