# Generated by Django 4.2.4 on 2023-10-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organizationkyc_establishment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkyc',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
