# Generated by Django 4.2.4 on 2023-12-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organizationdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='mobile_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
