# Generated by Django 4.2.4 on 2023-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organizationvisithistory_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
