# Generated by Django 4.2.4 on 2023-12-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0009_alter_organizationvisithistory_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkyc',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiting_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
