# Generated by Django 4.2.4 on 2023-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_organizationkyc_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranch',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
