# Generated by Django 4.2.4 on 2023-12-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationbranch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationbranch',
            name='status',
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='lock_branch',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='LOCK_BRANCH_CHOICES', max_length=10),
        ),
    ]
