# Generated by Django 4.2.4 on 2024-01-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_organizationvisithistorywithcreatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='departed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationVisitHistoryWithCreatedAt',
        ),
    ]
