# Generated by Django 4.2.4 on 2024-01-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_organizationvisithistory_departed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVisitHistoryWithCreatedAt',
            fields=[
                ('organizationvisithistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.organizationvisithistory')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'History with Created At',
                'verbose_name_plural': 'Histories with Created At',
            },
            bases=('organization.organizationvisithistory', models.Model),
        ),
        migrations.AlterField(
            model_name='organizationvisithistory',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
