# Generated by Django 4.2.4 on 2024-01-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_organizationbranch_lock_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationkyc',
            name='PAN_VAT_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='citizenship',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='contact_person_full_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='licenses',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='registration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
    ]
