# Generated by Django 4.2.4 on 2024-01-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_organizationkyc_pan_vat_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkyc',
            name='contact_person_full_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='organization_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='ward_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='whatsapp_viber_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
