# Generated by Django 4.2.4 on 2024-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_organizationkyc_contact_person_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkyc',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
