# Generated by Django 4.2.4 on 2024-01-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_organizationkyc_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationvisithistory',
            options={'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
    ]
