# Generated by Django 4.2.4 on 2024-01-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_organizationvisithistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationkyc',
            name='social_media_links',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
