# Generated by Django 4.2.4 on 2024-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_organizationvisithistory_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
