# Generated by Django 4.2.4 on 2024-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_organizationvisithistory_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
