# Generated by Django 4.2.4 on 2024-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_organizationbranch_branch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranch',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
