# Generated by Django 4.2.4 on 2024-01-19 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0027_organizationbranch_mobile_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_device', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('computer', 'Computer'), ('other', 'Other')], default='other', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_org', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
