# Generated by Django 4.2.4 on 2024-01-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_organizationvisithistory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
