# Generated by Django 4.2.4 on 2024-01-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_device_create_at_device_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
            ],
        ),
    ]
