# Generated by Django 4.2.4 on 2024-01-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/%Y/'),
        ),
    ]
