# Generated by Django 4.2.4 on 2024-01-27 06:57

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_organizationvisithistory_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('terms_and_conditions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faqs', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization Content',
                'verbose_name_plural': 'Organization Contents',
            },
        ),
    ]
