# Generated by Django 4.2.4 on 2024-01-27 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0034_organizationcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcontent',
            options={'verbose_name': 'Org Content', 'verbose_name_plural': 'Org Contents'},
        ),
        migrations.RemoveField(
            model_name='organizationcontent',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='organizationcontent',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
