# Generated by Django 4.2.4 on 2024-01-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_alter_organizationcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationkyc',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
