# Generated by Django 4.2.4 on 2024-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_organizationkyc_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
