# Generated by Django 4.2.4 on 2024-01-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_organizationvisithistory_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationvisithistory',
            name='accept',
        ),
    ]
