# Generated by Django 4.2.4 on 2024-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_adsbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsbanner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='adsbanner',
            name='image',
            field=models.ImageField(default=1, upload_to='ads_banners/'),
            preserve_default=False,
        ),
    ]
