# Generated by Django 4.2.4 on 2024-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_alter_organizationkyc_ward_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranch',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_qr/%Y/'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
