# Generated by Django 4.2.4 on 2024-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0045_alter_organizationbranch_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
