# Generated by Django 4.2.4 on 2024-02-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0048_alter_organizationkycdocument_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationVisitHistoryWithCreatedAt',
        ),
    ]
