# Generated by Django 4.2.4 on 2024-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0049_delete_organizationvisithistorywithcreatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationvisithistory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationvisithistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
