# Generated by Django 4.2.4 on 2024-02-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0050_organizationvisithistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationkyc',
            options={'verbose_name': 'Organization KYC', 'verbose_name_plural': 'Organization KYC'},
        ),
    ]
