# Generated by Django 4.2.4 on 2024-02-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0051_alter_organizationkyc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='visit_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Scan', 'Scan')], max_length=10, null=True),
        ),
    ]
