# Generated by Django 4.2.4 on 2024-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0052_organizationvisithistory_visit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_guest', models.IntegerField()),
                ('number_of_child_guest', models.IntegerField()),
                ('number_of_room', models.IntegerField()),
                ('type_of_id', models.CharField(max_length=200)),
                ('id_number', models.IntegerField()),
                ('advanced_payment', models.IntegerField()),
                ('remaining_payment', models.IntegerField()),
                ('checkout_date', models.DateField()),
                ('payment_method', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
