# Generated by Django 4.2.4 on 2024-04-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0053_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
