# Generated by Django 4.2.4 on 2024-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0054_alter_guest_checkout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='payment_method',
            new_name='paymentmethod',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='advanced_payment',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='number_of_child_guest',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='number_of_guest',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='number_of_room',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='remaining_payment',
        ),
        migrations.AddField(
            model_name='guest',
            name='advancedPayment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='numAdultguest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='numChildguest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='numofroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='remainingPayment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='type_of_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
